### ISSUE TITLE
adding tags

### ISSUE THREAD

**Issue by mad-ranger** [plebbit/temporary-default-subplebbits#4]
would it be possible to add tags/hashtags to the default list similar to what is planned for multisubs?
for example:
```
{
  "address": "meta.plebchan.eth",
  "tags": ["plebchan"]
}
```
i'm running @topplebbitposts on twitter and wanted to extend its reach by adding common hashtags to its posts
if that's not in the scope of this repo, it's okay, i can also create my own repo for this use case, i just wondered if it would be generally useful

**Comment by estebanabaroa** [comment]
we have to start using the multisub schema for the default subs eventually, so yes we can add tags, it won't break anything. if you want to do a PR for adding tags that's OK I will merge it, it won't break any of the apps.

**Comment by estebanabaroa** [comment]
we should start using https://github.com/plebbit/temporary-default-subplebbits/blob/master/multisub.json for the default sub which uses the `Multisub` schema, reason being we should start getting used to it and find problems with it, to prepare for custom multisubs and more than 1 default feed. It's possible to add tags, languages, features (like sfw) 

I left the other file subplebbits.json there until all clients have migrated

the schema is a work in progress but should be something like:

```js
Multisub /* (IPNS record Multisub.address) */ {
  title?: string
  description?: string
  subplebbits: MultisubSubplebbit[]
  createdAt: number
  updatedAt: number
  signature: Signature // signature of the Multisub update by the multisub owner to protect against malicious gateway
}
MultisubSubplebbit { // this metadata is set by the owner of the Multisub, not the owner of the subplebbit
  address: Address
  title?: string
  description?: string 
  languages?: string[] // client can detect language and hide/show subplebbit based on it
  locations?: string[] // client can detect location and hide/show subplebbit based on it
  features?: string[] // client can detect user's SFW setting and hide/show subplebbit based on it
  tags?: string[] // arbitrary keywords used for search
}
PlebbitDefaults { // fetched once when app first load, a dictionary of default settings
  multisubAddresses: {[multisubName: string]: Address}
  // plebbit has 3 default multisubs
  multisubAddresses.all: Address // the default subplebbits to show at url plebbit.eth/p/all
  multisubAddresses.crypto: Address // the subplebbits to show at url plebbit.eth/p/crypto
  multisubAddresses.search: Address // list of thousands of semi-curated subplebbits to "search" for in the client (only search the Multisub metadata, don't load each subplebbit)
}
```
